source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0‘
target 'ChineseGirl_Example' do
  pod 'ChineseGirl', :path => '../'
  pod 'UIFastTabBarController'
  pod 'WJFastDialogView'
  pod 'RouterManager'
  pod 'UIFastTableView'
  pod 'WJFastScrollViewPoint'
  pod 'IQKeyboardManager'
  pod 'UICommonTools'
  pod 'SVProgressHUD'
  pod 'NSDictionary+Accessors'
  pod 'FLAnimatedImage', '~> 1.0'
  # pod 'ZFPlayer'
  pod 'WJGlobalTimer'
  pod 'Masonry'
  pod 'WJPlayer'
end
